// <auto-generated />
using System;
using BitSchedulerCore.Data.BitTimeScheduler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitSchedulerCore.Migrations
{
    [DbContext(typeof(BitScheduleDbContext))]
    [Migration("20250216200811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.Property<int>("BitReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitReservationId"));

                    b.Property<int?>("BitDayId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SlotLength")
                        .HasColumnType("int");

                    b.Property<int>("StartBlock")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BitReservationId");

                    b.HasIndex("BitDayId");

                    b.ToTable("BitReservations");
                });

            modelBuilder.Entity("BitTimeScheduler.BitDay", b =>
                {
                    b.Property<int>("BitDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitDayId"));

                    b.Property<long>("BitsHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("BitsLow")
                        .HasColumnType("bigint");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.HasKey("BitDayId");

                    b.HasIndex("ClientId", "Date")
                        .IsUnique();

                    b.ToTable("BitDays");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.HasOne("BitTimeScheduler.BitDay", null)
                        .WithMany("Reservations")
                        .HasForeignKey("BitDayId");
                });

            modelBuilder.Entity("BitTimeScheduler.BitDay", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
