// <auto-generated />
using System;
using BitSchedulerCore.Data.BitTimeScheduler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitSchedulerCore.Migrations
{
    [DbContext(typeof(BitScheduleDbContext))]
    [Migration("20260528230000_AddBitResourceScheduleRange")]
    partial class AddBitResourceScheduleRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Property<int>("BitClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitClientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BitClientId");

                    b.ToTable("BitClients");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.Property<int>("BitReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitReservationId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("int");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SlotLength")
                        .HasColumnType("int");

                    b.Property<int>("StartBlock")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BitReservationId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitResourceId");

                    b.ToTable("BitReservations");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Property<int>("BitResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitResourceId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("int");

                    b.Property<int>("BitResourceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BitResourceId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitResourceTypeId");

                    b.ToTable("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.Property<int>("BitResourceScheduleRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitResourceScheduleRangeId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("int");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BitResourceScheduleRangeId");

                    b.HasIndex("BitClientId", "BitResourceId", "StartDate", "EndDate")
                        .IsUnique();

                    b.HasIndex("BitResourceId", "StartDate", "EndDate");

                    b.ToTable("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Property<int>("BitResourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitResourceTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BitResourceTypeId");

                    b.ToTable("BitResourceTypes");
                });

            modelBuilder.Entity("BitTimeScheduler.BitDay", b =>
                {
                    b.Property<int>("BitDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitDayId"));

                    b.Property<long>("BitsHigh")
                        .HasColumnType("bigint");

                    b.Property<long>("BitsLow")
                        .HasColumnType("bigint");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.HasKey("BitDayId");

                    b.HasIndex("ClientId", "Date")
                        .IsUnique();

                    b.ToTable("BitDays");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResources")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResourceType", "BitResourceType")
                        .WithMany("BitResources")
                        .HasForeignKey("BitResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResourceType");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");

                    b.Navigation("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Navigation("BitResources");
                });
#pragma warning restore 612, 618
        }
    }
}
