// <auto-generated />
using System;
using BitSchedulerCore.Data.BitTimeScheduler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitSchedulerCore.Migrations
{
    [DbContext(typeof(BitScheduleDbContext))]
    [Migration("20260619210005_AddBitEvents")]
    partial class AddBitEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Property<int>("BitClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitClientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BitClientId");

                    b.ToTable("BitClients");
                });

            modelBuilder.Entity("BitSchedulerCore.BitDay", b =>
                {
                    b.Property<int>("BitDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitDayId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<byte[]>("DayData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Metadata")
                        .HasColumnType("bigint");

                    b.HasKey("BitDayId");

                    b.HasIndex("ClientId", "Date")
                        .IsUnique();

                    b.ToTable("BitDays");
                });

            modelBuilder.Entity("BitSchedulerCore.BitEvent", b =>
                {
                    b.Property<int>("BitEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitEventId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndHexGridId")
                        .HasColumnType("integer");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("RequiresReturnTransportation")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresTransportation")
                        .HasColumnType("boolean");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StartHexGridId")
                        .HasColumnType("integer");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BitEventId");

                    b.HasIndex("BitResourceId", "StartDateTime");

                    b.HasIndex("BitClientId", "BitResourceId", "StartDateTime", "EndDateTime");

                    b.ToTable("BitEvents");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.Property<int>("BitReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitReservationId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("BitDayId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SlotLength")
                        .HasColumnType("integer");

                    b.Property<int>("StartBlock")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BitReservationId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitDayId");

                    b.HasIndex("BitResourceId");

                    b.ToTable("BitReservations");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Property<int>("BitResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BitResourceId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitResourceTypeId");

                    b.ToTable("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.Property<int>("BitResourceScheduleRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceScheduleRangeId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BitResourceScheduleRangeId");

                    b.HasIndex("BitResourceId", "StartDate", "EndDate");

                    b.HasIndex("BitClientId", "BitResourceId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Property<int>("BitResourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BitResourceTypeId");

                    b.ToTable("BitResourceTypes");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HexGridVersionId")
                        .HasColumnType("integer");

                    b.Property<double>("HexRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Q")
                        .HasColumnType("integer");

                    b.Property<int>("R")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("AreaName", "IsActive");

                    b.HasIndex("HexGridVersionId", "Q", "R")
                        .IsUnique();

                    b.ToTable("HexGridCells");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridCellVertex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HexGridCellId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("VertexOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HexGridCellId", "VertexOrder")
                        .IsUnique();

                    b.ToTable("HexGridCellVertices");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridNeighbor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("HexGridCellId")
                        .HasColumnType("integer");

                    b.Property<int>("NeighborHexGridCellId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NeighborHexGridCellId");

                    b.HasIndex("HexGridCellId", "Direction")
                        .IsUnique();

                    b.ToTable("HexGridNeighbors");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridSearchRing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HexGridCellId")
                        .HasColumnType("integer");

                    b.Property<int>("NearbyHexGridCellId")
                        .HasColumnType("integer");

                    b.Property<int>("RingDistance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NearbyHexGridCellId");

                    b.HasIndex("HexGridCellId", "NearbyHexGridCellId")
                        .IsUnique();

                    b.HasIndex("HexGridCellId", "RingDistance");

                    b.ToTable("HexGridSearchRings");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HexRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxLongitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxPrecomputedRingDistance")
                        .HasColumnType("integer");

                    b.Property<double>("MinLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MinLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("OriginLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("OriginLongitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AreaName", "IsActive");

                    b.ToTable("HexGridVersions");
                });

            modelBuilder.Entity("BitSchedulerCore.BitEvent", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitEvents")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitEvents")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitDay", null)
                        .WithMany("Reservations")
                        .HasForeignKey("BitDayId");

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResources")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResourceType", "BitResourceType")
                        .WithMany("BitResources")
                        .HasForeignKey("BitResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResourceType");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridCell", b =>
                {
                    b.HasOne("BitSchedulerCore.HexGrid.HexGridVersion", "HexGridVersion")
                        .WithMany("Cells")
                        .HasForeignKey("HexGridVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HexGridVersion");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridCellVertex", b =>
                {
                    b.HasOne("BitSchedulerCore.HexGrid.HexGridCell", "HexGridCell")
                        .WithMany("Vertices")
                        .HasForeignKey("HexGridCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HexGridCell");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridNeighbor", b =>
                {
                    b.HasOne("BitSchedulerCore.HexGrid.HexGridCell", "HexGridCell")
                        .WithMany("Neighbors")
                        .HasForeignKey("HexGridCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.HexGrid.HexGridCell", "NeighborHexGridCell")
                        .WithMany("NeighborOf")
                        .HasForeignKey("NeighborHexGridCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HexGridCell");

                    b.Navigation("NeighborHexGridCell");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridSearchRing", b =>
                {
                    b.HasOne("BitSchedulerCore.HexGrid.HexGridCell", "HexGridCell")
                        .WithMany("SearchRings")
                        .HasForeignKey("HexGridCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.HexGrid.HexGridCell", "NearbyHexGridCell")
                        .WithMany("NearbySearchRings")
                        .HasForeignKey("NearbyHexGridCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HexGridCell");

                    b.Navigation("NearbyHexGridCell");
                });

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Navigation("BitEvents");

                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");

                    b.Navigation("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitDay", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Navigation("BitEvents");

                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Navigation("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridCell", b =>
                {
                    b.Navigation("NearbySearchRings");

                    b.Navigation("NeighborOf");

                    b.Navigation("Neighbors");

                    b.Navigation("SearchRings");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("BitSchedulerCore.HexGrid.HexGridVersion", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
