// <auto-generated />
using System;
using BitSchedulerCore.Data.BitTimeScheduler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitSchedulerCore.Migrations
{
    [DbContext(typeof(BitScheduleDbContext))]
    partial class BitScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Property<int>("BitClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitClientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BitClientId");

                    b.ToTable("BitClients");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.Property<int>("BitReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitReservationId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("BitDayId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SlotLength")
                        .HasColumnType("integer");

                    b.Property<int>("StartBlock")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BitReservationId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitDayId");

                    b.HasIndex("BitResourceId");

                    b.ToTable("BitReservations");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Property<int>("BitResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BitResourceId");

                    b.HasIndex("BitClientId");

                    b.HasIndex("BitResourceTypeId");

                    b.ToTable("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.Property<int>("BitResourceScheduleRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceScheduleRangeId"));

                    b.Property<int>("BitClientId")
                        .HasColumnType("integer");

                    b.Property<int>("BitResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BitResourceScheduleRangeId");

                    b.HasIndex("BitResourceId", "StartDate", "EndDate");

                    b.HasIndex("BitClientId", "BitResourceId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Property<int>("BitResourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitResourceTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BitResourceTypeId");

                    b.ToTable("BitResourceTypes");
                });

            modelBuilder.Entity("BitTimeScheduler.BitDay", b =>
                {
                    b.Property<int>("BitDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BitDayId"));

                    b.Property<byte[]>("DayData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<long>("Metadata")
                        .HasColumnType("bigint");

                    b.HasKey("BitDayId");

                    b.HasIndex("ClientId", "Date")
                        .IsUnique();

                    b.ToTable("BitDays");
                });

            modelBuilder.Entity("BitSchedulerCore.BitReservation", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitTimeScheduler.BitDay", null)
                        .WithMany("Reservations")
                        .HasForeignKey("BitDayId");

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitReservations")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResources")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResourceType", "BitResourceType")
                        .WithMany("BitResources")
                        .HasForeignKey("BitResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResourceType");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceScheduleRange", b =>
                {
                    b.HasOne("BitSchedulerCore.BitClient", "BitClient")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitSchedulerCore.BitResource", "BitResource")
                        .WithMany("BitResourceScheduleRanges")
                        .HasForeignKey("BitResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BitClient");

                    b.Navigation("BitResource");
                });

            modelBuilder.Entity("BitSchedulerCore.BitClient", b =>
                {
                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");

                    b.Navigation("BitResources");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResource", b =>
                {
                    b.Navigation("BitReservations");

                    b.Navigation("BitResourceScheduleRanges");
                });

            modelBuilder.Entity("BitSchedulerCore.BitResourceType", b =>
                {
                    b.Navigation("BitResources");
                });

            modelBuilder.Entity("BitTimeScheduler.BitDay", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
